### ISSUE TITLE
Install tutorial

### ISSUE THREAD

**Issue by frdteknikelektro** [jespino/mattermost-plugin-messages-queue#3]
How to install this via plugins upload.
It seems like there need to run some npm or anything

**Comment by gardinermichael** [comment]
Ok so:

1. Make sure you have go installed. https://go.dev/doc/install.
2. Download a zip of this deprecated version of [Mattermost Redux](https://github.com/mattermost/mattermost-redux). Unzip and rename the folder to `mattermost-redux`. Place it at `webapp/src/mattermost-redux`.  Go into the folder. `npm install`, `npm run build`.
3. Go two folders up to `webapp/`. `npm install`, `npm run build`.
4. Caveat: The previous two steps could be pointless.
5.  Go one folder up to the root directory. Run this [go command](https://stackoverflow.com/questions/71507321/go-1-18-build-error-on-mac-unix-syscall-darwin-1-13-go253-golinkname-mus) if you get a _go:linkname must refer to declared function or variable_ error: `go get -u golang.org/x/sys`.
6. Run `make dist` in the root folder. It should make a package in the `dist/` folder.
7. `tar -xf` the file in your plugins folder on the server before going into the admin console to enable it. I guess in your case you would be uploading the `tar.gz` file via the plugin uploads button.
8. (bonus) Get incredibly annoyed with permissions and randomly fiddle with which tool you use to upload the package until you luck into the right user role.

**Comment by vmohir** [comment]
This could be a great plugin but there seems to be no way to install it easily.

**Comment by gardinermichael** [comment]
Just run `go get -u golang.org/x/sys` and then `make dist`

**Comment by footsim** [comment]
@gardinermichael Hi, I'm not able to build plugin, getting different errors. Maybe I shoud use some specific versions for go, npm, etc.?

**Comment by gardinermichael** [comment]
What error are you getting? FYI the plugin is a bit buggy and we ended up uninstalling it.On Dec 7, 2022, at 08:14, footsim ***@***.***> wrote:﻿
@gardinermichael Hi, I'm not able to build plugin, getting different errors. Maybe I shoud use some specific versions for go, npm, etc.?

**Comment by footsim** [comment]
Hi, please look at attachment 
[make fail.txt](https://github.com/jespino/mattermost-plugin-messages-queue/files/10183718/make.fail.txt)

**Comment by gardinermichael** [comment]
It doesn't look like the error I was getting relating to Go. Looking at the log, my inclination would be to clear your cache and try a lower version of Node with nvm? Maybe 12 or 14?
